# This file was generated by GoReleaser. DO NOT EDIT.
cask "wyk" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "0f3bc70a20ab96f6aaf21326fd1d42118df21020964c5db68d56bba1321b1f2e"
      url "https://github.com/jimbottle/would-you-kindly/releases/download/v#{version}/wyk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e836802f38bbbfe3e648c23ba226cc1fa7fcd877e66f902ed4bcdb7000e75f25"
      url "https://github.com/jimbottle/would-you-kindly/releases/download/v#{version}/wyk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e200b2cbb4c9715c13301f5574ca5e96884f1c3ea38df5d715002479283d512"
      url "https://github.com/jimbottle/would-you-kindly/releases/download/v#{version}/wyk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bcb795297baea9bba1f0bbca305dd2e7b0c1a204eafe1129108e5902f6faf6a"
      url "https://github.com/jimbottle/would-you-kindly/releases/download/v#{version}/wyk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wyk"
  desc "Terminal UI over the bd issue tracker with an agent/human handoff convention"
  homepage "https://github.com/jimbottle/would-you-kindly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wyk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wyk"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    wyk drives the `bd` (beads) issue tracker and needs it on your PATH.
    Install bd separately: https://github.com/gastownhall/beads
  EOS
end
